import { Link } from 'react-router-dom';
import { useCustodyStore, getPref } from '@/features/custody/data/repository';
import type { ConnectedPortfolio } from '@/features/connected/data/useConnectedPortfolio';
import type { ActivityLink } from '@/features/connected/domain/activity';
import { AssetValue } from '@/features/connected/presentation/AssetValue';
import { chainIdentity, tokenName } from '@/features/connected/presentation/identity';
import { Surface } from '@/shared/components/ui/GlassCard';
import { TokenLogo } from '@/shared/components/ui/EntityLogo';
import { MoneyValue, PercentValue, QuantityValue } from '@/shared/components/ui/FinancialValue';
import { Badge } from '@/shared/components/ui/Badge';
import { Disclosure } from '@/shared/components/ui/Disclosure';
import { costSummary, COST_STATUS } from '../domain/summary';
import { COST_PREF, type CostBook } from '../domain/book';
export function CostSummaryPanel({ portfolio, links }: { portfolio: ConnectedPortfolio; links: ActivityLink[] }) {
 useCustodyStore();
 const { rows } = costSummary(portfolio, getPref<CostBook>(COST_PREF)?.value, links);
 const identity = (row: typeof rows[number]) => <div className="flex min-w-0 items-center gap-3"><TokenLogo logo={row.asset.icon} symbol={row.asset.symbol} name={tokenName(row.asset.symbol, row.asset.name)} size={34} networkLogo={row.chains.size === 1 ? chainIdentity(row.asset.chain).logo : undefined} networkName={row.chains.size === 1 ? chainIdentity(row.asset.chain).name : undefined} /><div className="min-w-0"><span className="block text-sm font-semibold">{tokenName(row.asset.symbol, row.asset.name)}</span><span className="mt-1 block text-[11px] text-muted">{[...row.chains].map(c => chainIdentity(c).name).join(' · ')}</span></div></div>;
 const state = (row: typeof rows[number]) => row.status !== 'ready' ? <span title={row.issues[0]?.reason}><Badge tone="warn">{COST_STATUS[row.status as keyof typeof COST_STATUS]}</Badge></span> : null;
 const gain = (row: typeof rows[number]) => <div className="flex flex-col gap-1"><MoneyValue value={row.pnl} signed tone="auto" /><PercentValue value={row.pnlPct} className="text-xs" />{row.valuation.unknown !== '0' && row.pnl !== null && <span className="text-[10px] text-muted">فقط بخش دارای بهای خرید</span>}</div>;
 return <Surface as="section" aria-labelledby="dashboard-cost-title" className="cost-summary min-w-0 p-4 md:p-5">
  <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 id="dashboard-cost-title" className="text-base font-bold">بهای خرید و سود و زیان</h2><Link className="inline-flex min-h-11 items-center text-xs font-semibold text-accent" to="/accounting">سوابق و اصلاح خریدها</Link></div>
  {!rows.length ? <p className="text-sm text-muted">دارایی قابل محاسبه‌ای موجود نیست.</p> : <>
   <div className="hidden xl:block"><table className="data-table w-full"><caption className="sr-only">بهای خرید موجودی باقی‌مانده و سود و زیان باز رمزارزها</caption><thead><tr>{['دارایی', 'موجودی', 'قیمت فعلی', 'میانگین خرید', 'بهای تمام‌شده', 'ارزش روز', 'سود/زیان', 'سهم'].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.asset.key}><td><Link to="/accounting">{identity(row)}</Link><div className="mt-2">{state(row)}</div></td><td><QuantityValue value={row.quantity.toNumber()} /></td><td><MoneyValue value={row.price} /></td><td><MoneyValue value={row.avgCost} /></td><td><MoneyValue value={row.basis} />{row.valuation.unknown !== '0' && row.basis !== null && <span className="block text-[10px] text-muted">بخش مشخص</span>}</td><td><AssetValue stale={row.stale} value={row.priced ? row.value.toNumber() : null} primaryClassName="text-sm" /></td><td>{gain(row)}</td><td><PercentValue value={row.share} signed={false} tone="none" /></td></tr>)}</tbody></table></div>
   <div className="divide-y divide-divider xl:hidden">{rows.map(row => <article key={row.asset.key} className="space-y-4 py-4 first:pt-0 last:pb-0"><div className="flex items-start justify-between gap-3">{identity(row)}<div className="max-w-[45%] text-end text-xs"><QuantityValue value={row.quantity.toNumber()} unit={tokenName(row.asset.symbol)} /></div></div><div className="grid grid-cols-2 gap-4"><div><p className="mb-1 text-[11px] text-muted">ارزش روز</p><AssetValue stale={row.stale} value={row.priced ? row.value.toNumber() : null} primaryClassName="text-base font-bold" /></div><div className="text-end"><p className="mb-1 text-[11px] text-muted">سود و زیان باز</p>{gain(row)}</div></div>{state(row)}<Disclosure summary="بهای خرید و جزئیات"><dl className="grid grid-cols-2 gap-x-4 gap-y-4 py-2 text-sm">{[{ label: 'قیمت فعلی', value: <MoneyValue value={row.price} /> }, { label: 'میانگین خرید', value: <MoneyValue value={row.avgCost} /> }, { label: row.valuation.unknown !== '0' ? 'بهای بخش مشخص' : 'بهای تمام‌شده', value: <MoneyValue value={row.basis} /> }, { label: 'سهم پرتفولیو', value: <PercentValue value={row.share} signed={false} tone="none" /> }].map(item => <div key={item.label} className="min-w-0"><dt className="mb-1 text-[11px] text-muted">{item.label}</dt><dd className="break-words">{item.value}</dd></div>)}</dl>{row.valuation.unknown !== '0'&&<p className="text-xs text-muted">مقدار بدون بهای خرید: <QuantityValue value={Number(row.valuation.unknown)} unit={tokenName(row.asset.symbol)}/></p>}{row.issues.length>0&&<p className="mt-2 text-xs text-warn">{row.issues[0].reason}</p>}<Link to="/accounting" className="inline-flex min-h-11 items-center text-xs text-accent">مشاهده و اصلاح خریدها</Link></Disclosure></article>)}</div>
  </>}
 </Surface>;
}
