import { beforeEach, describe, expect, it, vi } from 'vitest';
import { readBorosAccount, readBorosPreview, clearBorosAccountCache } from '../../api/_borosAccount';
import { accountTotals, packAccount, unpackAccount, x18, toX18, CROSS } from '../../src/shared/boros/account';
import { borosRoot, borosHandle, accountAssets, accountBalances, accountPositions, accountSettlements, accountTransfers, accountSync } from '../fixtures/borosAccount';
const fetcher=vi.fn();
beforeEach(()=>{clearBorosAccountCache();vi.stubGlobal('fetch',fetcher);vi.stubEnv('BOROS_API_KEY','test-boros-key');fetcher.mockReset();fetcher.mockImplementation(async(url:string)=>{const path=new URL(url).pathname;const data=path.endsWith('/assets')?accountAssets:path.endsWith('/active-positions')?accountPositions:path.endsWith('/market-acc-infos-by-root')?accountBalances:path.endsWith('/settlement-events')?accountSettlements:path.endsWith('/transfer-logs')?accountTransfers:{results:[],syncStatus:accountSync};return new Response(JSON.stringify(data));});});
describe('Boros account units, identities and API contract',()=>{
 it('packs handles exactly like the published SDK, including leading-zero roots',()=>{const root='0x0000000000000000000000000000000000000001';const h=packAccount(root,255,65535,1);expect(h).toBe(root+'ffffff000001');expect(unpackAccount(h)).toEqual({root,accountId:255,tokenId:65535,marketId:1});expect(()=>packAccount(root,256,2,CROSS)).toThrow();});
 it('preserves fractional quantities and x18 USDT normalization without native-decimal rescaling',()=>{expect(toX18('12345.123456789012345678')).toBe('12345123456789012345678');expect(toX18('0.65')).toBe('650000000000000000');expect(x18('650000000000000000')).toBe(.65);expect(x18('1000000')).toBe(.000000000001);expect(x18(null)).toBeNull();expect(()=>toX18('0')).toThrow();expect(()=>toX18('0.0000000000000000001')).toThrow();});
 it('reads actual root-based schemas, keeps PnL streams separate, caches and never returns secrets',async()=>{const s=await readBorosAccount(borosRoot,0);expect(s.balances[0].equity).toBe(1.1);expect(s.positions[0]).toMatchObject({size:2,fixedApr:.05,unrealized:.02,realizedTrade:.01,settlement:.03,liquidationApr:.15});expect(s.settlements[0].amount).toBe(.029);expect(accountTotals(s)).toMatchObject({equityUsd:2200,unrealizedUsd:40,realizedTradeUsd:20,settlementUsd:60});expect(s.historyComplete).toBe(true);expect(JSON.stringify(s)).not.toContain('test-boros-key');expect(fetcher.mock.calls.every(([url,init])=>url.startsWith('https://api-boros.pendle.finance/apis/v1/')&&init.headers.Authorization==='Bearer test-boros-key')).toBe(true);await readBorosAccount(borosRoot,0);expect(fetcher).toHaveBeenCalledTimes(6);});
 it('deduplicates concurrent refreshes',async()=>{await Promise.all([readBorosAccount(borosRoot,0),readBorosAccount(borosRoot,0)]);expect(fetcher).toHaveBeenCalledTimes(6);});
 it('rejects a response belonging to another root instead of displaying its balances',async()=>{fetcher.mockImplementation(async(url:string)=>new Response(JSON.stringify(url.includes('active-positions')?{...accountPositions,results:[{...accountPositions.results[0],marketAcc:packAccount('0x2222222222222222222222222222222222222222',0,2,CROSS)}]}:accountAssets)));await expect(readBorosAccount(borosRoot,0)).rejects.toThrow();});
 it('retains unknown USD valuation and marks incomplete history after an optional provider failure',async()=>{fetcher.mockImplementation(async(url:string)=>{if(url.includes('settlement-events'))return new Response('',{status:429});const data=url.includes('/assets')?{results:[{tokenId:2,symbol:'WETH',usdPrice:null,metadata:{}}]}:url.includes('active-positions')?accountPositions:url.includes('market-acc-infos-by-root')?accountBalances:url.includes('transfer-logs')?accountTransfers:{results:[],syncStatus:accountSync};return new Response(JSON.stringify(data));});const s=await readBorosAccount(borosRoot,0);expect(s.partial).toBe(true);expect(s.historyComplete).toBe(false);expect(accountTotals(s).equityUsd).toBeNull();});
 it('uses only simulation POST; converts collateral margin and signed short size without mistaking matched cost for a fee',async()=>{fetcher.mockResolvedValue(new Response(JSON.stringify({matched:{size:'-650000000000000000',rate:.08,cost:'900000000000000000'},postState:{marginRequired:'20000000000000000',liquidationApr:.12},priceImpact:.001,status:'FILLED',statusCode:'Succeed'})));const s=await readBorosPreview({marketAcc:borosHandle,marketId:1,side:1,size:toX18('.65'),tif:2,slippage:.005});expect(s).toMatchObject({matchedSize:.65,matchedApr:.08,margin:.02,liquidationApr:.12,success:true});expect(s).not.toHaveProperty('fees');expect(fetcher.mock.calls[0][0]).toContain('/simulations/place-order');expect(fetcher.mock.calls[0][1].method).toBe('POST');});
 it('does not present an unfilled FOK simulation as successful entry',async()=>{fetcher.mockResolvedValue(new Response(JSON.stringify({matched:{size:'0',rate:0},postState:{marginRequired:'0',liquidationApr:null},priceImpact:0,status:'NOT_FILLED',statusCode:'Succeed'})));const s=await readBorosPreview({marketAcc:borosHandle,marketId:1,side:0,size:toX18('1'),tif:2,slippage:.005});expect(s.success).toBe(false);expect(s.matchedSize).toBe(0);});
});
