import { persianTicker } from '@/shared/domain/yieldTokenIdentity';
import { faNumber } from '@/shared/utils/formatters';
import { MarketAssetIdentity,marketAssetName } from './MarketAssetIdentity';
import { PerpsIdentity } from './PerpsIdentity';
import { useState,useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Page, PageHeader } from '@/shared/components/layout/Page';
import { Surface } from '@/shared/components/ui/GlassCard';
import { Button } from '@/shared/components/ui/Button';
import { Field, Input } from '@/shared/components/ui/Input';
import { Notice } from '@/shared/components/ui/StateViews';
import { fetchJson, HttpError } from '@/repositories/remoteClient';
import { useCustody } from '@/features/custody/data/useCustody';
import { saveHolding, getCustodySnapshot } from '@/features/custody/data/repository';
import { lighterAccounts, lighterMarkets, ondoMarkets, type PerpMarket } from '../domain/model';
const fmt = (n: number | null) => n === null || !Number.isFinite(n) ? 'نامشخص' : faNumber(n, { maximumFractionDigits: 6 });
const message = (e: unknown) => e instanceof HttpError && e.status===429 ? 'درخواست‌های زیادی ارسال شده؛ کمی بعد دوباره تلاش کنید' : 'دریافت اطلاعات انجام نشد';
function Account({ address, label, onRemove,mainnet=false }: { address: string; label: string; onRemove: () => Promise<void>;mainnet?:boolean }) {
 const q = useQuery({queryKey:[mainnet?'lighter-mainnet-account':'lighter-robinhood-account',address.toLowerCase()],queryFn:()=>fetchJson<unknown>(`/api/integrations?op=${mainnet?'lighter-mainnet-account':'lighter-account'}&address=${encodeURIComponent(address)}`,{timeoutMs:15000}),staleTime:30000,refetchInterval:30000,retry:1});
 const [removing,setRemoving]=useState(false),[error,setError]=useState('');
 const accounts = lighterAccounts(q.data,address);
 return <Surface className="p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><div className="min-w-0"><h2 className="font-bold">{label}</h2><p dir="ltr" className="mt-2 break-all text-xs text-muted">{address}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" loading={q.isFetching} onClick={()=>void q.refetch()}>به‌روزرسانی</Button><Button size="sm" variant="outline" loading={removing} onClick={async()=>{setRemoving(true);try{await onRemove();}catch{setError('حذف اتصال انجام نشد');}finally{setRemoving(false);}}}>حذف اتصال</Button></div></div>
 {error&&<Notice tone="warn">{error}</Notice>}{q.isPending&&<p className="text-sm text-muted">در حال دریافت حساب…</p>}{q.isError&&<Notice tone={q.data?'stale':'warn'}>{message(q.error)}{q.data?'؛ دادهٔ قبلی نمایش داده می‌شود.':''}</Notice>}
 {q.isSuccess&&!accounts.length&&<Notice>حساب فعالی برای این آدرس در این شبکه پیدا نشد.</Notice>}
 {accounts.map(a=><section key={a.index} className="border-t border-divider pt-4 space-y-3"><h3 className="text-sm font-semibold">حساب {fmt(a.index)}</h3><div className="grid grid-cols-2 gap-4"><div><p className="text-xs text-muted">ارزش حساب ({mainnet?'یو‌اس‌دی‌سی':'یو‌اس‌دی‌جی'})</p><p className="mt-2 font-bold">{fmt(a.equity)}</p></div><div><p className="text-xs text-muted">موجودی قابل استفاده ({mainnet?'یو‌اس‌دی‌سی':'یو‌اس‌دی‌جی'})</p><p className="mt-2 font-bold">{fmt(a.available)}</p></div></div>{mainnet&&<div className="space-y-3"><h4 className="text-sm font-semibold">دارایی‌های اسپات و وثیقه</h4>{a.assets.length?a.assets.map(t=><div key={t.symbol} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-divider p-3"><MarketAssetIdentity symbol={t.symbol}/><div className="space-y-1 text-xs"><p>موجودی: {fmt(t.balance)}</p><p>قفل‌شده: {fmt(t.locked)}</p><p>وثیقه: {fmt(t.margin)}</p></div></div>):<p className="text-xs text-muted">دارایی با موجودی مثبت یافت نشد.</p>}</div>}{a.positions.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['نماد','جهت','تعداد','قیمت ورود',mainnet?'سود و زیان تحقق‌نیافته (یو‌اس‌دی‌سی)':'سود و زیان تحقق‌نیافته (یو‌اس‌دی‌جی)','قیمت لیکویید'].map(h=><th key={h} className="p-3 text-start whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{a.positions.map((p,i)=><tr key={`${p.symbol}-${i}`} className="border-t border-divider"><td className="p-3"><MarketAssetIdentity symbol={p.symbol} robinhood={!mainnet}/></td><td className="p-3">{p.side==='long'?'لانگ':'شورت'}</td><td className="p-3">{fmt(p.size)}</td><td className="p-3">{fmt(p.entry)}</td><td className="p-3">{fmt(p.pnl)}</td><td className="p-3">{p.liquidation===0?'—':fmt(p.liquidation)}</td></tr>)}</tbody></table></div>:<p className="text-xs text-muted">پوزیشن بازی وجود ندارد.</p>}</section>)}
 </Surface>;
}
function PerpsContent({ provider,network='robinhood',mode='perp' }: { provider: 'lighter' | 'ondo';network?:'mainnet'|'robinhood';mode?:'perp'|'spot'|'assets' }) {
 const lighter=provider==='lighter',mainnet=lighter&&network==='mainnet',showAccounts=lighter&&(!mainnet||mode==='assets');const title=lighter?(mainnet?mode==='spot'?'بازار اسپات لایتر':mode==='assets'?'دارایی‌های لایتر':'بازار پرپچوال لایتر':'لایتر — شبکهٔ رابین‌هود'):'اوندو پرپس';const platformId=mainnet?'lighter-mainnet':'lighter-robinhood';const custody=useCustody();const [address,setAddress]=useState(''),[label,setLabel]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const holdings=custody.holdings.filter(h=>h.kind==='platform'&&h.platformId===platformId&&!h.archivedAt&&h.address);
 const q=useQuery({queryKey:mainnet?['perps-markets','lighter-mainnet',mode]:['perps-markets',provider],queryFn:async()=>{if(lighter)return lighterMarkets(await fetchJson<unknown>(`/api/integrations?op=${mainnet?'lighter-mainnet-markets':'lighter-markets'}`,{timeoutMs:15000}),mode==='spot'?'spot':'perp');const data=await fetchJson<{markets:unknown;prices:unknown}>('/api/integrations?op=ondo-markets',{timeoutMs:15000});return ondoMarkets(data.markets,data.prices);},enabled:mode!=='assets',staleTime:60000,refetchInterval:60000,retry:1});
 async function add(){setError('');setBusy(true);try{const a=address.trim();if(!/^0x[0-9a-fA-F]{40}$/.test(a))throw Error('آدرس عمومی EVM معتبر وارد کنید');const existing=getCustodySnapshot().holdings.find(h=>h.kind==='platform'&&h.platformId===platformId&&h.address?.toLowerCase()===a.toLowerCase());if(existing&&!existing.archivedAt)throw Error('این حساب قبلاً اضافه شده است');const now=Date.now();await saveHolding({id:existing?.id??crypto.randomUUID(),kind:'platform',platformId,address:a,label:label.trim()||(mainnet?'حساب لایتر':'حساب لایتر رابین‌هود'),createdAt:existing?.createdAt??now,updatedAt:now,archivedAt:null});setAddress('');setLabel('');}catch(e){setError(e instanceof Error?e.message:'ذخیره انجام نشد');}finally{setBusy(false);}}
 const markets:PerpMarket[]=(q.data??[]).filter(m=>[m.symbol,persianTicker(m.symbol),marketAssetName(m.symbol)].some(value=>value.toLowerCase().includes(search.trim().toLowerCase())));
 return <Page><PageHeader title={title} subtitle={lighter?(mainnet?'لایتر اصلی؛ اطلاعات عمومی و فقط‌خواندنی':'موجودی و پوزیشن‌های حساب روی شبکهٔ رابین‌هود'):'بازارهای قرارداد دائمی اوندو'}/><Surface className="p-5 flex flex-wrap items-center justify-between gap-3"><PerpsIdentity provider={mainnet?'lighter-mainnet':provider}/><p className="text-sm text-muted">{lighter?'اتصال فقط با آدرس عمومی؛ بدون کلید خصوصی یا امضای تراکنش.':'قیمت‌ها از رابط رسمی اوندو دریافت می‌شوند.'}</p><a className="text-sm font-semibold text-accent" href={lighter?(mainnet?mode==='spot'?'https://app.lighter.xyz/trade/LIT_USDC':'https://app.lighter.xyz/trade/LIT':'https://robinhoodchain.lighter.xyz/trade/LIT'):'https://app.ondoperps.xyz/'} target="_blank" rel="noopener noreferrer">باز کردن پلتفرم ↗</a></Surface>
 {showAccounts?<><Surface className="p-5"><form className="grid gap-4 md:grid-cols-3" onSubmit={e=>{e.preventDefault();void add();}}><Field label="نام حساب"><Input maxLength={80} disabled={busy} value={label} onChange={e=>setLabel(e.target.value)} placeholder="حساب من"/></Field><Field label="آدرس عمومی کیف پول"><Input dir="ltr" autoComplete="off" maxLength={42} disabled={busy} value={address} onChange={e=>setAddress(e.target.value)} placeholder="0x…"/></Field><Button type="submit" className="self-end" loading={busy} disabled={!custody.loaded||!address.trim()}>افزودن حساب</Button>{error&&<div className="md:col-span-3"><Notice tone="warn">{error}</Notice></div>}</form></Surface>{holdings.map(h=><Account mainnet={mainnet} key={h.id} address={h.address!} label={h.label} onRemove={()=>saveHolding({...h,archivedAt:Date.now(),updatedAt:Date.now()})}/>)}<Notice>مبالغ این حساب با واحد {mainnet?'یو‌اس‌دی‌سی':'یو‌اس‌دی‌جی'} نمایش داده می‌شوند و فعلاً در مجموع دلاری داشبورد محاسبه نمی‌شوند.</Notice></>:!lighter?<Notice title="اتصال حساب شخصی">این صفحه بازارهای عمومی را نمایش می‌دهد. اتصال موجودی شخصی با شناسهٔ کلید به‌تنهایی در مستندات فعلی تأیید نشده است؛ برای مشاهدهٔ حساب از پلتفرم رسمی وارد شوید.</Notice>:null}
 {mode!=='assets'&&<Surface className="p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="font-bold">{mode==='spot'?'بازارهای اسپات':'بازارهای پرپچوال'}</h2><Button size="sm" variant="outline" loading={q.isFetching} onClick={()=>void q.refetch()}>به‌روزرسانی قیمت‌ها</Button></div><Input aria-label="جست‌وجوی بازار" withSearchIcon value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجوی نماد"/>{q.isPending&&<p className="text-sm text-muted">در حال دریافت بازارها…</p>}{q.isError&&<Notice tone={q.data?'stale':'warn'}>{message(q.error)}{q.data?'؛ قیمت‌های قبلی نمایش داده می‌شوند.':''}</Notice>}{q.isSuccess&&!markets.length&&<p className="text-sm text-muted">بازاری پیدا نشد.</p>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{markets.map(m=><div key={m.symbol} className="rounded-xl border border-divider p-4"><MarketAssetIdentity symbol={m.symbol} logo={m.logo} robinhood={lighter&&!mainnet}/><p className="mt-2 text-sm">{mode==='spot'?'قیمت:':'قیمت مارک:'} {fmt(m.price)} {mainnet&&mode==='spot'&&m.quote?persianTicker(m.quote):lighter?(mainnet?'یو‌اس‌دی‌سی':'یو‌اس‌دی‌جی'):'دلار'}</p>{m.change!==null&&<p className="mt-2 text-xs text-muted">تغییر ۲۴ ساعت: {fmt(m.change)}٪</p>}</div>)}</div></Surface>}</Page>;
}

export default function PerpsPage({provider,initialTab='robinhood'}:{provider:'lighter'|'ondo';initialTab?:'perp'|'spot'|'assets'|'robinhood'}){
 const [tab,setTab]=useState(initialTab);
 useEffect(()=>setTab(initialTab),[initialTab]);
 if(provider==='ondo')return <PerpsContent provider="ondo"/>;
 return <div className="space-y-5"><Surface className="p-2"><div role="tablist" aria-label="بخش‌های لایتر" className="grid grid-cols-2 gap-2 sm:grid-cols-4">{([['perp','بازار پرپچوال'],['spot','بازار اسپات'],['assets','دارایی‌ها'],['robinhood','رابین‌هود']] as const).map(([value,label])=><button key={value} type="button" role="tab" aria-selected={tab===value} className={`rounded-xl px-3 py-3 text-sm font-semibold ${tab===value?'bg-accent text-white':'text-muted hover:bg-surface-2'}`} onClick={()=>setTab(value)}>{label}</button>)}</div></Surface><div role="tabpanel"><PerpsContent key={tab} provider="lighter" mode={tab==='robinhood'?'perp':tab} network={tab==='robinhood'?'robinhood':'mainnet'}/></div></div>;
}
