import { ArrowDownLeft,ArrowUpRight,ArrowLeftRight,ShieldCheck } from 'lucide-react';
import { Surface } from '@/shared/components/ui/GlassCard';
import { Badge } from '@/shared/components/ui/Badge';
import { TokenLogo,LogoImage } from '@/shared/components/ui/EntityLogo';
import { MoneyValue } from '@/shared/components/ui/FinancialValue';
import { chainIdentity,tokenName,operationNames,tokenQuantity } from './identity';
import { dateTime } from './ConnectedPage';
import { isInternal,type Activity,type ActivityLink } from '../domain/activity';
import { visibleTransaction,visibleTransfer,tokenLogo } from '../domain/visibility';
import type { ChainInfo } from '../domain/model';
const labels:Record<string,string>={DEPOSIT:'واریز به آرکوس',WITHDRAWAL:'برداشت از آرکوس',TRANSFER:'انتقال زیرحساب',bridge_swap:'بریج همراه سواپ',bridge:'بریج بین شبکه‌ها',arcus_withdrawal:'آرکوس ← کیف پول',arcus_deposit:'کیف پول ← آرکوس'};
export function ActivityList({rows,links=[],addresses=[],chains=[]}:{rows:Activity[];links?:ActivityLink[];addresses?:string[];chains?:ChainInfo[]}) {
 const visible=rows.filter(r=>!r.tx||visibleTransaction(r.tx));
 const byKey=new Map(visible.map(r=>[r.key,r]));
 const children=new Set(links.filter(l=>byKey.has(l.from)&&byKey.has(l.to)).map(l=>l.to));
 function card(row:Activity,nested=false){const tx=row.tx,chain=tx?chainIdentity(tx.chain,chains):null;
 const receiving=tx?.type==='receive'||row.kind==='DEPOSIT',sending=tx?.type==='send'||row.kind==='WITHDRAWAL';const Icon=receiving?ArrowDownLeft:sending?ArrowUpRight:tx?.type==='approve'?ShieldCheck:ArrowLeftRight;
 return <div className={nested?'mt-4 border-s-2 border-accent/30 ps-3':'space-y-3'}><div className="flex items-center gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full ${receiving?'bg-positive/10 text-positive':sending?'bg-surface-2 text-ink':'bg-accent/10 text-accent'}`}><Icon className="h-5 w-5"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{row.provider==='arcus'?labels[row.kind]??'فعالیت آرکوس':operationNames[row.kind]??'فعالیت قرارداد'}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-muted"><LogoImage src={chain?.logo??'/logos/platform-arcus.png'} label={chain?.name??'آرکوس'} size={15}/>{chain?.name??'آرکوس'}</p></div><Badge tone={['confirmed','APPLIED'].includes(row.status)?'gain':'warn'}>{['confirmed','APPLIED'].includes(row.status)?'تأییدشده':['pending','PENDING'].includes(row.status)?'در انتظار':['failed','FAILED'].includes(row.status)?'ناموفق':'در حال بررسی'}</Badge></div>
 <ul className="space-y-2">{tx?.transfers.filter(t=>visibleTransfer(t,tx.chain)).map((t,i)=><li key={i} className="flex items-center gap-3 rounded-field bg-surface-2 p-3"><TokenLogo logo={tokenLogo({...t,chain:t.chain??tx.chain})} symbol={t.symbol} name={tokenName(t.symbol,t.name??t.symbol)} networkLogo={chain?.logo??null} networkName={chain?.name??''} size={30}/><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{tokenName(t.symbol,t.name??t.symbol)}</p><p className="mt-1 text-xs text-muted">{t.direction==='in'?'دریافت':t.direction==='out'?'ارسال':'انتقال'}</p></div><div className="min-w-0 max-w-[55%] text-end"><p dir="ltr" className={`break-words text-sm font-semibold ${t.direction==='in'?'text-positive':'text-ink'}`} title={t.quantity??undefined}>{t.direction==='in'?'+':t.direction==='out'?'-':''}{tokenQuantity(t.quantity)} {t.symbol}</p><MoneyValue value={t.value} className="mt-1 text-xs text-muted"/></div></li>)}</ul>{row.amount&&<MoneyValue value={Number(row.amount)}/>}<div className="flex flex-wrap items-center justify-between gap-2 text-xs text-muted"><span>{row.label}</span><span>{Number.isFinite(row.at)&&row.at>0?dateTime(row.at):'زمان نامشخص'}</span></div>
 {tx&&isInternal(tx,addresses)&&<Badge tone="info">انتقال داخلی</Badge>}{tx&&<details className="text-xs text-muted"><summary className="cursor-pointer">جزئیات</summary><div className="mt-2 space-y-2 rounded-field bg-surface-2 p-3">{tx.protocol&&<p className="inline-flex items-center gap-2"><LogoImage src={tx.protocolIcon} label={tx.protocol} size={18}/>{tx.protocol}</p>}<p>کارمزد <MoneyValue value={tx.fee}/></p><bdi dir="ltr" className="block break-all">{tx.hash||tx.id}</bdi>{tx.transfers.filter(t=>visibleTransfer(t,tx.chain)).map((t,i)=>t.contract&&<bdi key={i} dir="ltr" className="block break-all">{t.symbol} · {t.contract}</bdi>)}</div></details>}</div>;
 }
 return <ul className="space-y-3">{visible.filter(r=>!children.has(r.key)).map(row=>{const link=links.find(l=>l.from===row.key&&byKey.has(l.to));return <li key={row.key}><Surface className="p-4">{link&&<p className="mb-3 text-xs font-semibold text-accent">{labels[link.kind]} · {link.proof?'تطبیق API '+(link.proof==='lifi'?'لای‌فای':'ریلی'):'ارتباط تأییدشده'}</p>}{card(row)}{link&&card(byKey.get(link.to)!,true)}</Surface></li>;})}</ul>;
}
