import { Fragment,useState,useCallback } from 'react';
import { ArrowDownLeft,ArrowUpRight,ArrowLeftRight,ShieldCheck,ChevronLeft } from 'lucide-react';
import { Sheet } from '@/shared/components/ui/Sheet';
import { Badge } from '@/shared/components/ui/Badge';
import { TokenLogo,LogoImage } from '@/shared/components/ui/EntityLogo';
import { MoneyValue } from '@/shared/components/ui/FinancialValue';
import { AssetValue } from './AssetValue';
import { chainIdentity,tokenName,operationNames,tokenQuantity,platformName } from './identity';
import { dateTime } from './ConnectedPage';
import { activityDay } from '../domain/activityView';
import { isInternal,type Activity,type ActivityLink } from '../domain/activity';
import { visibleTransaction,visibleTransfer,tokenLogo } from '../domain/visibility';
import type { ChainInfo } from '../domain/model';
const labels:Record<string,string>={DEPOSIT:'واریز به آرکوس',WITHDRAWAL:'برداشت از آرکوس',TRANSFER:'انتقال زیرحساب',bridge_swap:'بریج همراه سواپ',bridge:'بریج بین شبکه‌ها',arcus_withdrawal:'برداشت آرکوس',arcus_deposit:'واریز آرکوس'};
export function ActivityList({rows,links=[],addresses=[],chains=[]}:{rows:Activity[];links?:ActivityLink[];addresses?:string[];chains?:ChainInfo[]}) {
 const [selected,setSelected]=useState<Activity|null>(null);const close=useCallback(()=>setSelected(null),[]);
 const visible=rows.filter(r=>!r.tx||visibleTransaction(r.tx));const byKey=new Map(visible.map(r=>[r.key,r]));
 const children=new Set(links.filter(l=>byKey.has(l.from)&&byKey.has(l.to)).map(l=>l.to));
 function name(row:Activity){return row.provider==='arcus'?labels[row.kind]??'فعالیت آرکوس':operationNames[row.kind]??'فعالیت قرارداد';}
 function flows(row:Activity){return (row.tx?.transfers.length?row.tx.transfers:row.tx?.approvals??[]).filter(t=>visibleTransfer(t,row.tx?.chain??''));}
 function card(row:Activity,nested=false){const tx=row.tx,chain=tx?chainIdentity(tx.chain,chains):null,assets=flows(row);
 const receiving=tx?.type==='receive'||row.kind==='DEPOSIT',sending=tx?.type==='send'||row.kind==='WITHDRAWAL';const Icon=receiving?ArrowDownLeft:sending?ArrowUpRight:['approve','revoke'].includes(row.kind)?ShieldCheck:ArrowLeftRight;
 const main=assets.find(t=>t.direction==='in')??assets[0];const confirmed=['confirmed','APPLIED'].includes(row.status);
 return <button type="button" onClick={()=>setSelected(row)} aria-label={`جزئیات ${name(row)} · ${row.label}`} className={`activity-native-row flex min-h-20 w-full items-center gap-3 rounded-field p-3 text-start transition-colors hover:bg-surface-2 active:bg-accent/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent ${nested?'mt-1 border-s-2 border-accent/30':' '}`}>
 <span className={`relative flex h-11 w-11 shrink-0 items-center justify-center rounded-full ${receiving?'bg-positive/10 text-positive':'bg-surface-2 text-muted'}`}><Icon className="h-5 w-5"/><span className="absolute -bottom-1 -end-1 rounded-full bg-card p-0.5"><LogoImage src={chain?.logo??'/logos/platform-arcus.png'} label={chain?.name??'آرکوس'} size={17}/></span></span>
 <span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{name(row)}</span><span className="mt-1 block truncate text-xs text-muted">{main?tokenName(main.symbol,main.name??main.symbol):row.label}</span><span className="mt-1 block text-[11px] text-muted">{Number.isFinite(row.at)&&row.at>0?new Date(row.at).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'}):'—'}{!confirmed&&<span className="ms-2 text-warn">{['pending','PENDING'].includes(row.status)?'در انتظار':'ناموفق'}</span>}</span></span>
 <span className="min-w-0 max-w-[49%] text-end">{main?<><span dir="ltr" className={`block break-words text-xs font-semibold ${receiving?'text-positive':'text-ink'}`}>{main.direction==='in'?'+':main.direction==='out'?'-':''}{tokenQuantity(main.quantity)} {main.symbol}</span><AssetValue value={main.value} className="mt-1 text-end" primaryClassName="text-xs"/></>:<AssetValue value={row.amount?Number(row.amount):null} className="text-end" primaryClassName="text-sm"/>}</span><ChevronLeft className="h-3.5 w-3.5 shrink-0 text-subtle"/>
 </button>;
 }
 const top=visible.filter(r=>!children.has(r.key));const selectedFlows=selected?flows(selected):[];
 return <><ul className="native-activity-list space-y-0">{top.map((row,index)=>{const link=links.find(l=>l.from===row.key&&byKey.has(l.to));const day=activityDay(row.at),newDay=index===0||activityDay(top[index-1].at)!==day;return <Fragment key={row.key}>{newDay&&<li className="pb-2 pt-5"><h3 className="px-3 text-xs font-semibold text-muted">{day}</h3></li>}<li className="border-b border-divider last:border-b-0">{link&&<p className="px-3 pt-3 text-[11px] font-semibold text-accent">{labels[link.kind]} · {link.proof?'تطبیق خودکار':'تأییدشده'}</p>}{card(row)}{link&&card(byKey.get(link.to)!,true)}</li></Fragment>;})}</ul>
 <Sheet open={!!selected} onClose={close} title={selected?name(selected):'جزئیات تراکنش'}><div className="space-y-4"><Badge tone={selected&&['confirmed','APPLIED'].includes(selected.status)?'gain':'warn'}>{selected&&['confirmed','APPLIED'].includes(selected.status)?'تأییدشده':'در حال بررسی'}</Badge><p className="text-xs text-muted">{selected?.label} · {selected&&Number.isFinite(selected.at)?dateTime(selected.at):'—'}</p>{selected?.tx&&isInternal(selected.tx,addresses)&&<Badge tone="info">انتقال داخلی</Badge>}<ul className="divide-y divide-divider">{selectedFlows.map((t,i)=>{const n=chainIdentity(t.chain??selected?.tx?.chain??'',chains);return <li key={i} className="flex flex-wrap items-center gap-3 py-3"><TokenLogo logo={tokenLogo({...t,chain:t.chain??selected?.tx?.chain??''})} symbol={t.symbol} name={tokenName(t.symbol,t.name??t.symbol)} networkLogo={n.logo} networkName={n.name} size={38}/><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{tokenName(t.symbol,t.name??t.symbol)}</p><bdi dir="ltr" className="block break-words text-xs text-muted">{tokenQuantity(t.quantity)} {t.symbol}</bdi></div><AssetValue value={t.value} primaryClassName="text-sm" className="text-end"/></li>;})}</ul>{selected?.tx?.protocol&&<p className="flex items-center gap-2 text-sm"><LogoImage src={selected.tx.protocolIcon} label={selected.tx.protocol} size={24}/>{platformName(selected.tx.protocol)}</p>}{selected?.tx&&<div className="space-y-3 rounded-field bg-surface-2 p-3 text-xs"><p>کارمزد <MoneyValue value={selected.tx.fee}/></p>{[['شناسهٔ تراکنش',selected.tx.hash||selected.tx.id],['آدرس مبدأ',selected.tx.from||selectedFlows.find(t=>t.direction==='in')?.sender||selectedFlows.find(t=>t.direction==='in')?.address],['آدرس مقصد',selected.tx.to||selectedFlows.find(t=>t.direction==='out')?.recipient||selectedFlows.find(t=>t.direction==='out')?.address]].map(([label,value])=>value&&<div key={label}><p className="mb-1 text-muted">{label}</p><bdi dir="ltr" className="block break-all text-ink">{value}</bdi></div>)}</div>}</div></Sheet></>;
}
