import { Link } from 'react-router-dom';
import { RefreshCw, Wallet, Sparkles } from 'lucide-react';
import { Section, Surface } from '@/shared/components/ui/GlassCard';
import { MoneyValue } from '@/shared/components/ui/FinancialValue';
import { LogoImage } from '@/shared/components/ui/EntityLogo';
import { Badge } from '@/shared/components/ui/Badge';
import { Notice } from '@/shared/components/ui/StateViews';
import { Button, buttonClass } from '@/shared/components/ui/Button';
import { Disclosure } from '@/shared/components/ui/Disclosure';
import { PositionsList } from './PositionsList';
import { dateTime } from './ConnectedPage';
import type { ConnectedPortfolio } from '../data/useConnectedPortfolio';
export function PortfolioSummary({ portfolio:p }: { portfolio:ConnectedPortfolio }) {
  return <><Surface variant="focal" className="space-y-5 p-5 md:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-muted">ارزش دارایی‌های متصل</p><MoneyValue value={p.total} state={p.stale?'stale':'ready'} className="mt-2 text-3xl font-bold md:text-4xl" /><div className="mt-2 flex flex-wrap gap-2"><Badge tone="brand">زریون + آرکوس</Badge>{p.partial && <Badge tone="warn">مجموع ناقص</Badge>}{p.stale && <Badge tone="warn">برخی داده‌ها قدیمی است</Badge>}</div></div><Button variant="outline" icon={<RefreshCw />} onClick={() => void p.refresh()}>به‌روزرسانی</Button></div><Disclosure summary="مبنای مجموع"><p className="text-xs leading-6 text-muted">ارزش کیف پول‌های زریون و حساب‌های اصلی آرکوس؛ موجودی دستی، سناریوها و تست‌نت جدا هستند.</p></Disclosure><div className="flex flex-wrap gap-2"><Link to="/wallets" className={buttonClass('primary','md')}><Wallet/>کیف پول‌ها و تراکنش‌ها</Link><Link to="/assistant" className={buttonClass('outline','md')}><Sparkles/>تحلیل با دستیار</Link><Link to="/arcus" className={buttonClass('outline','md')}>حساب آرکوس</Link></div></Surface>
  {p.partial && <Notice tone="warn">مجموع ناقص است؛ منابع یا قیمت‌های دریافت‌نشده صفر فرض نشده‌اند.</Notice>}
  {!p.wallets.length && !p.arcus.length && <Notice>یک کیف پول یا حساب آرکوس اضافه کنید.</Notice>}
  <Section title="منابع پرتفولیو" id="portfolio-sources"><div className="grid gap-3 md:grid-cols-2">{p.wallets.map(s => <Surface key={s.holding.id} className="p-4"><div className="flex items-center gap-3"><LogoImage src="/logos/platform-zerion.png" label="زریون" size={32} square/><div className="min-w-0 flex-1"><p className="font-semibold text-ink">{s.holding.label}</p><p className="text-xs text-muted">زریون · {s.state?.data ? dateTime(s.state.data.fetchedAt) : 'در انتظار دریافت'}</p></div><MoneyValue value={s.value} state={s.stale?'stale':'ready'}/></div>{s.state?.error && <p className="mt-2 text-xs text-warn">{s.state.error}</p>}<details className="mt-4"><summary className="cursor-pointer text-sm text-accent">توکن‌ها، شبکه‌ها و پوزیشن‌ها</summary>{s.state?.data && <PositionsList data={s.state.data}/>}</details></Surface>)}
  {p.arcus.map(s => <Surface key={s.holding.id} className="space-y-3 p-4"><div className="flex items-center gap-3"><LogoImage src="/logos/platform-arcus.png" label="آرکوس" size={32} square/><div className="min-w-0 flex-1"><p className="font-semibold text-ink">{s.holding.label}</p><p className="text-xs text-muted">آرکوس · زیرحساب {s.holding.arcus!.accountIndex} · {s.state?.account.fetchedAt ? dateTime(s.state.account.fetchedAt) : 'در انتظار دریافت'}</p></div><MoneyValue value={s.value} state={s.stale?'stale':'ready'}/></div>{s.holding.arcus!.env==='testnet' && <Badge tone="warn">آزمایشی؛ خارج از مجموع</Badge>}{s.state?.account.error && <p className="text-xs text-warn">{s.state.account.error.message}</p>}<ul className="divide-y divide-divider">{s.state?.positions.data?.map(position => <li key={position.marketId} className="flex flex-wrap items-center justify-between gap-2 py-2 text-sm"><bdi dir="ltr">{position.marketDisplayName}</bdi><Badge>{position.side==='LONG'?'خرید':'فروش'} · اهرم <bdi dir="ltr">{position.leverage}×</bdi></Badge><MoneyValue value={Number(position.unrealizedPnl)} signed tone="auto"/></li>)}</ul><Link to="/arcus" className="text-sm text-accent">پوزیشن‌ها و تاریخچهٔ آرکوس</Link></Surface>)}</div></Section>
  <p className="text-xs text-muted"><Link to="/accounting" className="text-accent">سوابق ثبت دستی</Link> · خارج از مجموع واقعی</p></>;
}
