import { useEffect, useRef, useState } from 'react';
import { RefreshCw, Unplug } from 'lucide-react';
import { useBorosAccount, hydrateBorosAccount, selectBorosAccount, refreshBorosAccount, clearBorosAccount, accountIsStale } from '../data/useBorosAccount';
import { accountTotals, rootSchema, CROSS } from '@/shared/boros/account';
import { Surface } from '@/shared/components/ui/GlassCard';
import { Field, Input } from '@/shared/components/ui/Input';
import { Button } from '@/shared/components/ui/Button';
import { Metric, MetricGrid, MoneyValue, PercentValue, QuantityValue } from '@/shared/components/ui/FinancialValue';
import { Badge } from '@/shared/components/ui/Badge';
import { Disclosure } from '@/shared/components/ui/Disclosure';
import { EmptyState, Notice } from '@/shared/components/ui/StateViews';
import { TokenLogo } from '@/shared/components/ui/EntityLogo';
import { AssetValue } from '@/features/connected/presentation/AssetValue';
import { tokenName, chainIdentity } from '@/features/connected/presentation/identity';
import { normalizeDecimalInput } from '@/features/cost-basis/presentation/decimalInput';
import { borosAssetName, borosVenueName } from './borosLabels';
import { AccountHistory } from './AccountHistory';
import type { BorosMarket } from '../domain/types';
const date=(v:number|null)=>v===null?'—':new Intl.DateTimeFormat('fa-IR',{dateStyle:'short',timeStyle:'short'}).format(v);
const location:Record<string,string>={wallet:'کیف پول',cross_account:'حساب مشترک',isolated_account:'حساب جدا',amm:'استخر'};
const transferLabel=(v:string)=>v.split(' · ')[0].split('→').map(p=>location[p]??'انتقال').join(' ← ');
const statusLabel=(v:string)=>v.endsWith(' · success')?'انجام‌شده':v.endsWith(' · pending')?'در انتظار':'ناموفق';
type Tab='collateral'|'positions'|'orders'|'order-history'|'trade-history'|'settlements'|'transfers';
export function AccountTab({markets}:{markets:BorosMarket[]}) {
 const touched=useRef(false);const s=useBorosAccount();const [address,setAddress]=useState(s.root);const [id,setId]=useState(String(s.accountId));const [formError,setFormError]=useState<string|null>(null);
 const [tab,setTab]=useState<Tab>('collateral');const [token,setToken]=useState<number|null>(null);
 useEffect(()=>{void hydrateBorosAccount().then(()=>{if(!touched.current){setAddress(useBorosAccount.getState().root);setId(String(useBorosAccount.getState().accountId));}});void refreshBorosAccount();const t=setInterval(()=>{if(document.visibilityState==='visible')void refreshBorosAccount();},60000);return()=>clearInterval(t);},[]);
 const connect=async()=>{setFormError(null);try{await selectBorosAccount(address.trim(),Number(id));setToken(null);setTab('collateral');}catch{setFormError('آدرس یا شماره حساب معتبر نیست');}};
 const d=s.data;const stale=accountIsStale(s);const totals=d?accountTotals(d):null;const network=chainIdentity('arbitrum');
 const asset=(tokenId:number)=>d?.assets.find(a=>a.tokenId===tokenId);
 const usd=(v:number|null,tokenId:number)=>v!==null&&asset(tokenId)?.priceUsd!=null&&asset(tokenId)!.priceUsd!>0?v*asset(tokenId)!.priceUsd!:null;
 const label=(marketId:number)=>{const m=markets.find(m=>m.marketId===marketId);return m?`${borosAssetName(m.asset)} · ${borosVenueName(m.venue)}`:'بازار '+new Intl.NumberFormat('fa-IR').format(marketId);};
 const identity=(tokenId:number)=><div className="flex items-center gap-2 min-w-0"><TokenLogo logo={asset(tokenId)?.logo} symbol={asset(tokenId)?.symbol??''} name={tokenName(asset(tokenId)?.symbol??'')} networkLogo={network.logo} networkName={network.name} size={32}/><span className="text-sm font-semibold">{tokenName(asset(tokenId)?.symbol??'')}</span></div>;
 const funded=d?.balances.filter(b=>[b.cash,b.equity,b.margin].some(v=>v===null||v!==0)||d.positions.some(p=>p.handle===b.handle))??[];
 const ids=new Set([...funded.map(b=>b.tokenId),...d?.transfers.map(e=>e.tokenId)??[]]);
 const selected=(tokenId:number)=>token===null||token===tokenId;
 const positions=d?.positions.filter(p=>selected(p.tokenId))??[];
 const balances=funded.filter(b=>selected(b.tokenId));
 const tabs:{id:Tab;name:string}[]=[{id:'collateral',name:'وثیقه'},{id:'positions',name:`پوزیشن‌ها (${new Intl.NumberFormat('fa-IR').format(positions.length)})`},{id:'orders',name:'سفارش‌های باز'},{id:'order-history',name:'تاریخچه سفارش'},{id:'trade-history',name:'تاریخچه معامله'},{id:'settlements',name:'تاریخچه تسویه'},{id:'transfers',name:'واریز و برداشت'}];
 return <div className="boros-account space-y-4">
  <Surface className="p-4 space-y-3">
   <Disclosure summary={s.root?'مدیریت حساب':'اتصال حساب بوروس'} defaultOpen={!s.root}>
    <div className="grid gap-3 sm:grid-cols-[1fr_100px_auto] items-end pt-3"><Field label="آدرس حساب بوروس" error={formError}><Input value={address} dir="ltr" placeholder="آدرس کیف پول واریزکننده · 0x…" autoComplete="off" onChange={e=>{touched.current=true;setAddress(e.target.value);}} /></Field><Field label="شماره حساب"><Input dir="ltr" inputMode="numeric" value={id} onChange={e=>{touched.current=true;setId(normalizeDecimalInput(e.target.value));}}/></Field><Button onClick={()=>void connect()} disabled={s.loading||!rootSchema.safeParse(address.trim()).success||!/^[0-9]{1,3}$/.test(id)||Number(id)>255}>مشاهده حساب</Button></div>
    {s.root&&<Button className="mt-3" size="sm" variant="ghost" icon={<Unplug/>} onClick={()=>{void clearBorosAccount();setAddress('');setToken(null);}}>حذف اتصال</Button>}
   </Disclosure>
   {s.root&&<div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs text-muted">{s.accountId===0?'حساب اصلی':'حساب '+new Intl.NumberFormat('fa-IR').format(s.accountId)}<bdi dir="ltr" className="ms-2">{s.root.slice(0,6)}…{s.root.slice(-4)}</bdi></div><Button size="sm" variant="ghost" icon={<RefreshCw/>} disabled={s.loading||Date.now()<s.retryAt} onClick={()=>void refreshBorosAccount(true)}>{s.loading?'در حال دریافت…':'به‌روزرسانی'}</Button></div>}
  </Surface>
  {s.error&&<Notice tone="warn">{s.error}{d?'؛ آخرین داده حفظ شده است':''}</Notice>}
  {!d?<EmptyState message={s.loading?'در حال دریافت حساب…':s.root?'هنوز داده حساب دریافت نشده است':'آدرس حساب را وارد کنید.'}/>:<>
   <Surface variant="focal" className="p-4 md:p-5"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm font-semibold">پرتفولیوی بوروس</span><Badge tone={stale?'warn':d.partial?'neutral':'gain'}>{stale?'داده ذخیره‌شده':d.partial?'داده جزئی':'به‌روز'}</Badge></div><div className="mt-3 text-3xl font-bold"><AssetValue value={totals?.equityUsd} stale={stale}/></div><MetricGrid cols={3} className="mt-4"><Metric size="sm" label="مارجین آزاد" value={<MoneyValue value={totals?.freeMarginUsd}/>}/><Metric size="sm" label="سود تحقق‌نیافته" value={<MoneyValue value={totals?.unrealizedUsd} signed tone="auto"/>}/><Metric size="sm" label="اعتبار کارمزد" value={<MoneyValue value={d.gasBalanceUsd}/>}/></MetricGrid><p className="mt-3 text-xs text-muted">{date(d.syncedAt)}</p></Surface>
   {funded.some(b=>b.maintenanceBuffer!==null&&b.maintenanceBuffer<=0&&d.positions.some(p=>p.handle===b.handle))&&<Notice tone="warn">حاشیه نگهداری کافی نیست؛ حساب در معرض لیکوییدشدن است.</Notice>}
   {d.errors.map(e=><Notice key={e} tone="warn">{e}</Notice>)}
   <Surface className="overflow-hidden">
    <div role="tablist" onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const i=tabs.findIndex(t=>t.id===tab);const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowLeft'?1:-1)+tabs.length)%tabs.length;setTab(tabs[next].id);document.getElementById('boros-account-'+tabs[next].id)?.focus();}} aria-label="پرتفولیوی بوروس" className="boros-account-tabs flex overflow-x-auto border-b border-divider px-2">{tabs.map(t=><button key={t.id} id={'boros-account-'+t.id} aria-controls="boros-account-panel" role="tab" tabIndex={tab===t.id?0:-1} aria-selected={tab===t.id} onClick={()=>setTab(t.id)} className={`shrink-0 px-4 py-4 text-sm font-semibold border-b-2 transition-colors ${tab===t.id?'border-brand-500 text-brand-500 bg-brand-500/5':'border-transparent text-muted'}`}>{t.name}</button>)}</div>
    {ids.size>1&&<div className="flex flex-wrap gap-2 p-3 border-b border-divider" aria-label="فیلتر وثیقه"><button className="rounded-full bg-surface-2 px-3 py-2 text-xs" aria-pressed={token===null} onClick={()=>setToken(null)}>همه</button>{d.assets.filter(a=>ids.has(a.tokenId)).map(a=><button key={a.tokenId} className={`rounded-full px-3 py-2 ${token===a.tokenId?'bg-brand-500/10':'bg-surface-2'}`} aria-pressed={token===a.tokenId} onClick={()=>setToken(a.tokenId)}>{identity(a.tokenId)}</button>)}</div>}
    <div id="boros-account-panel" role="tabpanel" aria-labelledby={'boros-account-'+tab} className="p-4">
     {tab==='collateral'&&<div className="divide-y divide-divider">{balances.map(b=><div key={b.handle} className="py-4 first:pt-0 last:pb-0"><div className="flex flex-wrap items-center justify-between gap-3">{identity(b.tokenId)}<AssetValue value={usd(b.equity,b.tokenId)}/></div><p className="mt-2 text-xs text-muted">{b.marketId===CROSS?'مارجین مشترک':'مارجین جدا · '+label(b.marketId)} · آربیتروم</p><MetricGrid cols={3} className="mt-4"><Metric size="sm" label="موجودی وثیقه" value={<QuantityValue value={b.cash} digits={8} unit={tokenName(asset(b.tokenId)?.symbol??'')}/>}/><Metric size="sm" label="مارجین لازم" value={<MoneyValue value={usd(b.margin,b.tokenId)}/>}/><Metric size="sm" label="مارجین آزاد" value={<MoneyValue value={usd(b.freeMargin,b.tokenId)}/>}/></MetricGrid></div>)}{!balances.length&&<EmptyState message="وثیقه‌ای در این حساب ثبت نشده است؛ آدرس و شماره حساب واریز را بررسی کنید."/>}</div>}
     {tab==='positions'&&<>
      <div className="hidden xl:block overflow-x-auto"><table className="w-full text-sm text-start"><thead className="text-xs text-muted"><tr>{['بازار','حجم قرارداد','حساسیت نرخ','نرخ ثابت ورود','نرخ پایه','نرخ مارک','نرخ لیکوییدشدن','سود تحقق‌نیافته','مارجین'].map(h=><th key={h} className="text-start font-medium px-3 py-3 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{positions.map(p=>{const m=markets.find(m=>m.marketId===p.marketId);const fresh=!!m?.snapshotAt&&!stale&&Date.now()-m.snapshotAt<180000;const b=d.balances.find(b=>b.handle===p.handle);return <tr key={p.handle+p.marketId} className="border-t border-divider"><td className="p-3 min-w-40">{identity(p.tokenId)}<p className="mt-2 text-xs">{label(p.marketId)}</p><Badge tone={p.side==='long'?'gain':'loss'}>{p.side==='long'?'لانگ فاندینگ':'شورت فاندینگ'}</Badge></td><td className="p-3"><QuantityValue value={p.size} unit="واحد بازده"/></td><td className="p-3"><MoneyValue value={fresh&&p.size!==null?usd(p.size*Math.max(0,m!.maturity-Date.now()/1000)/(365*86400)*.01,p.tokenId):null}/><span className="block text-xs text-muted">برای ۱٪</span></td><td className="p-3"><PercentValue value={p.fixedApr===null?null:p.fixedApr*100} tone="none"/></td><td className="p-3"><PercentValue value={fresh?m!.floatingApr*100:null} tone="none"/></td><td className="p-3"><PercentValue value={fresh?m!.markApr*100:null} tone="none"/></td><td className="p-3"><PercentValue value={p.liquidationApr===null?null:p.liquidationApr*100} tone="none"/></td><td className="p-3"><MoneyValue value={usd(p.unrealized,p.tokenId)} signed tone="auto"/></td><td className="p-3"><MoneyValue value={usd(b?.margin??null,p.tokenId)}/><span className="block text-xs text-muted">{b?.marketId===CROSS?'مشترک حساب':'جدا'}</span></td></tr>})}</tbody></table></div>
      <div className="xl:hidden divide-y divide-divider">{positions.map(p=>{const m=markets.find(m=>m.marketId===p.marketId);const fresh=!!m?.snapshotAt&&!stale&&Date.now()-m.snapshotAt<180000;return <article key={p.handle+p.marketId} className="py-4 first:pt-0"><div className="flex flex-wrap items-center justify-between gap-3">{identity(p.tokenId)}<Badge tone={p.side==='long'?'gain':'loss'}>{p.side==='long'?'لانگ فاندینگ':'شورت فاندینگ'}</Badge></div><h3 className="mt-3 text-sm font-semibold">{label(p.marketId)}</h3><MetricGrid cols={2} className="mt-4"><Metric size="sm" label="حجم قرارداد" value={<QuantityValue value={p.size} unit="واحد بازده"/>}/><Metric size="sm" label="سود تحقق‌نیافته" value={<MoneyValue value={usd(p.unrealized,p.tokenId)} signed tone="auto"/>}/><Metric size="sm" label="نرخ ثابت ورود" value={<PercentValue value={p.fixedApr===null?null:p.fixedApr*100} tone="none"/>}/><Metric size="sm" label="نرخ لیکوییدشدن" value={<PercentValue value={p.liquidationApr===null?null:p.liquidationApr*100} tone="none"/>}/><Metric size="sm" label="مارجین حساب" value={<MoneyValue value={usd(d.balances.find(b=>b.handle===p.handle)?.margin??null,p.tokenId)}/>}/><Metric size="sm" label="نرخ پایه" value={<PercentValue value={fresh?m!.floatingApr*100:null} tone="none"/>}/><Metric size="sm" label="نرخ مارک" value={<PercentValue value={fresh?m!.markApr*100:null} tone="none"/>}/></MetricGrid></article>})}</div>
      {positions.length>0&&<Disclosure summary="جزئیات سود و تسویه"><div className="divide-y divide-divider">{positions.map(p=><div key={p.handle+p.marketId} className="py-3"><p className="text-sm font-semibold mb-3">{label(p.marketId)}</p><MetricGrid cols={2}><Metric size="sm" label="سود معاملات این بازار از ابتدا" value={<MoneyValue value={usd(p.realizedTrade,p.tokenId)} signed tone="auto"/>}/><Metric size="sm" label="تسویه فاندینگ این بازار از ابتدا" value={<MoneyValue value={usd(p.settlement,p.tokenId)} signed tone="auto"/>}/></MetricGrid></div>)}</div></Disclosure>}
      {!positions.length&&<EmptyState message="پوزیشن باز ندارید؛ وثیقه در زبانهٔ «وثیقه» نمایش داده می‌شود."/>}
     </>}
     {tab==='orders'&&<div className="divide-y divide-divider">{d.orders.filter(o=>{const m=markets.find(m=>m.marketId===o.marketId);return token===null||m?.tokenId===token;}).map(o=><div key={o.id} className="flex flex-wrap justify-between gap-3 py-3 text-sm"><span>{label(o.marketId)} · {o.side==='long'?'لانگ فاندینگ':'شورت فاندینگ'}</span><QuantityValue value={o.size} unit="واحد بازده"/><PercentValue value={o.rate===null?null:o.rate*100} tone="none"/></div>)}{!d.orders.length&&<EmptyState message="سفارش بازی ثبت نشده است."/>}</div>}
     {(tab==='order-history'||tab==='trade-history')&&<AccountHistory key={d.root+':'+d.accountId+':'+tab} account={d} kind={tab} token={token} label={label}/>}
     {(tab==='settlements'||tab==='transfers')&&<div className="divide-y divide-divider">{(tab==='settlements'?d.settlements:d.transfers).filter(e=>selected(e.tokenId)).sort((a,b)=>(b.at??0)-(a.at??0)).map(e=><div key={e.kind+e.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div className="space-y-2">{identity(e.tokenId)}<p className="text-sm">{e.kind==='settlement'?label(e.marketId!):transferLabel(e.kind)}</p><p className="text-xs text-muted">{date(e.at)}{e.kind!=='settlement'?' · '+statusLabel(e.kind):''}</p></div>{e.kind==='settlement'?<MoneyValue value={usd(e.amount,e.tokenId)} signed tone="auto"/>:<QuantityValue value={e.amount} unit={tokenName(asset(e.tokenId)?.symbol??'')}/>}</div>)}{!(tab==='settlements'?d.settlements:d.transfers).some(e=>selected(e.tokenId))&&<EmptyState message="رویدادی ثبت نشده است."/>}{!d.historyComplete&&<p className="pt-3 text-xs text-muted">آخرین رویدادهای دریافت‌شده</p>}</div>}
    </div>
   </Surface>
  </>}
 </div>;
}
