import { useEffect, useRef, useState } from 'react';
import { RefreshCw, Unplug } from 'lucide-react';
import { useBorosAccount, hydrateBorosAccount, selectBorosAccount, refreshBorosAccount, clearBorosAccount, accountIsStale } from '../data/useBorosAccount';
import { accountTotals, rootSchema } from '@/shared/boros/account';
import { Surface } from '@/shared/components/ui/GlassCard';
import { Field, Input } from '@/shared/components/ui/Input';
import { Button } from '@/shared/components/ui/Button';
import { Metric, MetricGrid, MoneyValue, PercentValue, QuantityValue } from '@/shared/components/ui/FinancialValue';
import { Badge } from '@/shared/components/ui/Badge';
import { Disclosure } from '@/shared/components/ui/Disclosure';
import { EmptyState, Notice } from '@/shared/components/ui/StateViews';
import { TokenLogo } from '@/shared/components/ui/EntityLogo';
import { AssetValue } from '@/features/connected/presentation/AssetValue';
import { tokenName, chainIdentity } from '@/features/connected/presentation/identity';
import { normalizeDecimalInput } from '@/features/cost-basis/presentation/decimalInput';
import { borosAssetName, borosVenueName } from './borosLabels';
import type { BorosMarket } from '../domain/types';
const date=(v:number|null)=>v===null?'—':new Intl.DateTimeFormat('fa-IR',{dateStyle:'short',timeStyle:'short'}).format(v);
const location:Record<string,string>={wallet:'کیف پول',cross_account:'حساب مشترک',isolated_account:'حساب جدا',amm:'استخر'};
const transferLabel=(v:string)=>v.split(' · ')[0].split('→').map(p=>location[p]??'انتقال').join(' ← ');
export function AccountTab({markets}:{markets:BorosMarket[]}) {
 const touched=useRef(false);const s=useBorosAccount();const [address,setAddress]=useState(s.root);const [id,setId]=useState(String(s.accountId));const [formError,setFormError]=useState<string|null>(null);
 useEffect(()=>{void hydrateBorosAccount().then(()=>{if(!touched.current){setAddress(useBorosAccount.getState().root);setId(String(useBorosAccount.getState().accountId));}});void refreshBorosAccount();const t=setInterval(()=>{if(document.visibilityState==='visible')void refreshBorosAccount();},60000);return()=>clearInterval(t);},[]);
 const connect=async()=>{setFormError(null);try{await selectBorosAccount(address.trim(),Number(id));}catch{setFormError('آدرس یا شماره حساب معتبر نیست');}};
 const d=s.data;const stale=accountIsStale(s);const totals=d?accountTotals(d):null;const network=chainIdentity('arbitrum');
 const asset=(tokenId:number)=>d?.assets.find(a=>a.tokenId===tokenId);
 const usd=(v:number|null,tokenId:number)=>v!==null&&asset(tokenId)?.priceUsd!=null&&asset(tokenId)!.priceUsd!>0?v*asset(tokenId)!.priceUsd!:null;
 const remaining=(p:NonNullable<typeof d>['positions'][number])=>{const m=markets.find(m=>m.marketId===p.marketId);const fresh=m?.snapshotAt&&Date.now()-m.snapshotAt<180000;if(stale||!fresh||!m||p.fixedApr===null||p.size===null||!Number.isFinite(m.floatingApr))return null;return usd((p.side==='long'?1:-1)*p.size*(m.floatingApr-p.fixedApr)*Math.max(0,m.maturity-Date.now()/1000)/(365*86400),p.tokenId);};
 const label=(marketId:number)=>{const m=markets.find(m=>m.marketId===marketId);return m?`${borosAssetName(m.asset)} · ${borosVenueName(m.venue)}`:'بازار '+new Intl.NumberFormat('fa-IR').format(marketId);};
 return <div className="space-y-4">
  <Surface className="p-4 space-y-3"><div className="grid gap-3 sm:grid-cols-[1fr_100px_auto] items-end"><Field label="آدرس حساب بوروس" error={formError}><Input value={address} dir="ltr" placeholder="0x…" autoComplete="off" onChange={e=>{touched.current=true;setAddress(e.target.value);}} /></Field><Field label="شماره حساب"><Input dir="ltr" inputMode="numeric" value={id} onChange={e=>{touched.current=true;setId(normalizeDecimalInput(e.target.value));}}/></Field><Button onClick={()=>void connect()} disabled={s.loading||!rootSchema.safeParse(address.trim()).success||!/^[0-9]{1,3}$/.test(id)||Number(id)>255}>مشاهده حساب</Button></div>
  {s.root&&<div className="flex flex-wrap justify-between gap-2"><span className="text-xs text-muted">شماره حساب {new Intl.NumberFormat('fa-IR').format(s.accountId)}</span><div className="flex gap-2"><Button size="sm" variant="ghost" icon={<RefreshCw/>} disabled={s.loading||Date.now()<s.retryAt} onClick={()=>void refreshBorosAccount(true)}>به‌روزرسانی</Button><Button size="sm" variant="ghost" icon={<Unplug/>} onClick={()=>{void clearBorosAccount();setAddress('');}}>حذف اتصال</Button></div></div>}</Surface>
  {s.error&&<Notice tone="warn">{s.error}{d?'؛ آخرین داده حفظ شده است':''}</Notice>}
  {!d?<EmptyState message={s.loading?'در حال دریافت حساب…':s.root?'هنوز داده حساب دریافت نشده است':'آدرس حساب را وارد کنید.'}/>:<>
   <Surface variant="focal" className="p-4 md:p-5"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm font-semibold">حساب بوروس</span><Badge tone={stale?'warn':d.partial?'neutral':'gain'}>{stale?'داده ذخیره‌شده':d.partial?'داده جزئی':'به‌روز'}</Badge></div><div className="mt-3 text-3xl font-bold"><AssetValue value={totals?.equityUsd} stale={stale}/></div><MetricGrid cols={3} className="mt-4"><Metric label="مارجین آزاد" value={<MoneyValue value={totals?.freeMarginUsd}/>}/><Metric label="سود تحقق‌نیافته" value={<MoneyValue value={totals?.unrealizedUsd} signed tone="auto"/>}/><Metric label="آخرین همگام‌سازی" value={<span className="text-xs">{date(d.syncedAt)}</span>}/></MetricGrid></Surface>
   {d.balances.some(b=>b.maintenanceBuffer!==null&&b.maintenanceBuffer<=0)&&<Notice tone="warn">حاشیه نگهداری کافی نیست؛ حساب در معرض لیکوییدشدن است.</Notice>}
   {d.errors.map(e=><Notice key={e} tone="warn">{e}</Notice>)}
   <div className="space-y-3">{d.balances.map(b=><Surface key={b.handle} className="p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3 min-w-0"><TokenLogo logo={asset(b.tokenId)?.logo} symbol={asset(b.tokenId)?.symbol??''} name={tokenName(asset(b.tokenId)?.symbol??'')} networkLogo={network.logo} networkName={network.name} size={36}/><div><p className="text-sm font-semibold">{tokenName(asset(b.tokenId)?.symbol??'')}</p><p className="text-xs text-muted">{b.marketId===0xffffff?'مارجین مشترک':'مارجین جدا'} · آربیتروم</p></div></div><AssetValue value={usd(b.equity,b.tokenId)}/></div><MetricGrid cols={3} className="mt-3"><Metric label="موجودی وثیقه" value={<QuantityValue value={b.cash} unit={tokenName(asset(b.tokenId)?.symbol??'')}/>}/><Metric label="مارجین لازم" value={<MoneyValue value={usd(b.margin,b.tokenId)}/>}/><Metric label="فاصله تا لیکوییدشدن" value={<MoneyValue value={usd(b.maintenanceBuffer,b.tokenId)} signed tone="auto"/>}/></MetricGrid></Surface>)}</div>
   <div className="space-y-3">{d.positions.length===0?<EmptyState message="پوزیشن باز ندارید."/>:d.positions.map(p=><Surface key={p.handle+':'+p.marketId} className="p-4 space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-bold">{label(p.marketId)}</h3><Badge tone={p.side==='long'?'gain':'loss'}>{p.side==='long'?'لانگ فاندینگ':'شورت فاندینگ'}{p.matured?' · سررسیدشده':''}</Badge></div><MetricGrid cols={3}><Metric label="حجم" value={<QuantityValue value={p.size} unit="واحد بازده"/>}/><Metric label="نرخ ثابت ورود" value={<PercentValue value={p.fixedApr===null?null:p.fixedApr*100} tone="none"/>}/><Metric label="نرخ لیکوییدشدن" value={<PercentValue value={p.liquidationApr===null?null:p.liquidationApr*100} tone="none"/>}/><Metric label="سود تحقق‌نیافته" value={<MoneyValue value={usd(p.unrealized,p.tokenId)} signed tone="auto"/>}/><Metric label="سود معاملات این بازار از ابتدا" value={<MoneyValue value={usd(p.realizedTrade,p.tokenId)} signed tone="auto"/>}/><Metric label="تسویه باقی‌مانده با فرض نرخ جاری، پیش از هزینه" value={<MoneyValue value={remaining(p)} signed tone="auto"/>}/><Metric label="تسویه فاندینگ این بازار از ابتدا" value={<MoneyValue value={usd(p.settlement,p.tokenId)} signed tone="auto"/>}/></MetricGrid></Surface>)}</div>
   <Disclosure summary="سفارش‌های باز"><div className="divide-y divide-divider">{d.orders.map(o=><div key={o.id} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span>{label(o.marketId)} · {o.side==='long'?'لانگ':'شورت'}</span><QuantityValue value={o.size} unit="واحد بازده"/><PercentValue value={o.rate===null?null:o.rate*100} tone="none"/></div>)}{!d.orders.length&&<EmptyState message="سفارش بازی ثبت نشده است."/>}</div></Disclosure>
   <Disclosure summary="تسویه‌ها و انتقال‌ها"><div className="divide-y divide-divider">{[...d.settlements,...d.transfers].sort((a,b)=>(b.at??0)-(a.at??0)).map(e=><div key={e.kind+e.id} className="py-3 flex flex-wrap justify-between gap-3 text-xs"><span>{e.kind==='settlement'?'تسویه · '+label(e.marketId!):transferLabel(e.kind)}<span className="block mt-1 text-muted">{date(e.at)}</span></span>{e.kind==='settlement'?<MoneyValue value={usd(e.amount,e.tokenId)} signed tone="auto"/>:<QuantityValue value={e.amount} unit={tokenName(asset(e.tokenId)?.symbol??'')}/>}</div>)}</div><p className="text-xs text-muted py-2">{d.historyComplete?'تاریخچه دریافت‌شده کامل است.':'آخرین رویدادها؛ تاریخچه ممکن است کامل نباشد.'} معادل دلار با قیمت فعلی وثیقه است؛ سود تاریخی دلاری نیست.</p></Disclosure>
  </>}
 </div>;
}
