import {useBorosPlan} from './useBorosPlan';
import {useEffect,useMemo,useState} from 'react';
import {useBorosAccount,refreshBorosAccount,accountIsStale} from '../data/useBorosAccount';
import {accountBudget} from '../domain/accountBudget';
import {entryCandidates} from '../domain/recommendations';
import {compareWithBudget,type PreviewDraft} from '../domain/workflow';
import type {BorosMarket,BorosDirection} from '../domain/types';
import {VerifiedOpportunities,type EntrySelection} from './VerifiedOpportunities';
import {OpportunitiesTab} from './OpportunitiesTab';
import {ComparisonTab} from './ComparisonTab';
import {Surface} from '@/shared/components/ui/GlassCard';
import {Field,Input,Select} from '@/shared/components/ui/Input';
import {Button} from '@/shared/components/ui/Button';
import {MoneyValue} from '@/shared/components/ui/FinancialValue';
import {Disclosure} from '@/shared/components/ui/Disclosure';
import {SegmentedControl} from '@/shared/components/ui/SegmentedControl';
import {normalizeDecimalInput} from '@/features/cost-basis/presentation/decimalInput';
import {tokenName} from '@/features/connected/presentation/identity';
import {MarketIdentity} from './MarketIdentity';
const number=(s:string)=>/^(?:\d+(?:\.\d*)?|\.\d+)$/.test(s)&&Number.isFinite(Number(s))?Number(s):null;
export function EntryRecommendations({markets,onSelect,onAccount,onInspect,active=true}:{markets:BorosMarket[];onSelect:(entry:EntrySelection)=>void;onAccount:()=>void;onInspect:(id:number,side:BorosDirection,draft?:PreviewDraft)=>void;active?:boolean}){
 const account=useBorosAccount();const plan=useBorosPlan();const {selected,mode,capital,capitalUnit,days,allocation,risk,gas,entrance}=plan;
 const setSelected=(v:string)=>plan.update({selected:v,...(capitalUnit==='asset'?{capital:''}:{})}),setMode=(v:'real'|'hypothetical')=>plan.update({mode:v}),setCapital=(v:string)=>plan.update({capital:v}),setDays=(v:string)=>plan.update({days:v}),setAllocation=(v:string)=>plan.update({allocation:v}),setRisk=(v:string)=>plan.update({risk:v}),setGas=(v:string)=>plan.update({gas:v}),setEntrance=(v:string)=>plan.update({entrance:v});
 const [view,setView]=useState<'all'|'recommend'|'compare'>('all');const [compareIds,setCompareIds]=useState<number[]>([]);
 useEffect(()=>{if(!active)return;void refreshBorosAccount();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refreshBorosAccount();},30000);return()=>clearInterval(timer);},[active]);
 const zones=[...new Map(markets.filter(m=>m.tokenId!==undefined&&m.status==='GOOD').map(m=>[String(m.tokenId),m])).values()];
 const fallback=zones.find(m=>(accountBudget(account.data,accountIsStale(account),m).budgetUsd??0)>0)||zones[0];
 const market=zones.find(m=>String(m.tokenId)===selected)||fallback;
 const budget=market?accountBudget(account.data,accountIsStale(account),market):null;
 const capitalUsd=mode==='real'?(budget?.budgetUsd??0):(number(capital)??0)*(capitalUnit==='asset'?(market?.collateralPriceUsd??0):1);
 const costs={feesUsd:number(entrance),gasUsd:number(gas),slippageUsd:0};
 const candidates=useMemo(()=>market&&(mode==='hypothetical'||budget?.available)?entryCandidates(markets,market.tokenId!,capitalUsd,number(allocation)??0,Number(days),costs):[],[markets,market,mode,budget?.available,capitalUsd,allocation,days,gas,entrance]);
 useEffect(()=>{setCompareIds(ids=>{const next=ids.filter(id=>markets.some(m=>m.marketId===id&&m.tokenId===market?.tokenId));return next.length===ids.length?ids:next;});},[markets,market?.tokenId]);
 const selectedMarkets=markets.filter(m=>compareIds.includes(m.marketId)&&m.tokenId===market?.tokenId);
 const input=(label:string,value:string,set:(v:string)=>void,suffix:string,placeholder?:string)=><Field label={label}><Input dir="ltr" inputMode="decimal" value={value} onChange={e=>set(normalizeDecimalInput(e.target.value))} suffix={suffix} placeholder={placeholder}/></Field>;
 const controls=<Surface className="p-4 space-y-4"><div className="flex flex-wrap justify-between items-center gap-3"><h3 className="font-bold text-sm">بودجهٔ مشترک بررسی</h3><Button size="sm" variant="ghost" onClick={onAccount}>مشاهده حساب من</Button></div><SegmentedControl label="مبنای پیشنهادها" fill value={mode} onChange={setMode} options={[{value:'real',label:'حساب واقعی'},{value:'hypothetical',label:'سرمایهٔ فرضی'}]}/><div className="grid gap-3 sm:grid-cols-2"><Field label="وثیقه"><Select value={market?.tokenId??''} onChange={e=>{setSelected(e.target.value);setCompareIds([]);}}>{zones.map(m=><option key={m.tokenId} value={m.tokenId}>{tokenName(m.collateralSymbol??m.asset)}</option>)}</Select></Field>{mode==='real'?<div><p className="text-xs text-muted">مارجین آزاد همین وثیقه</p><MoneyValue value={budget?.budgetUsd} digits={2} className="mt-2 text-xl font-bold" state={accountIsStale(account)?'stale':'ready'}/></div>:<><Field label="واحد سرمایهٔ فرضی"><Select value={capitalUnit} onChange={e=>plan.update({capitalUnit:e.target.value as 'usd'|'asset',capital:''})}><option value="usd">دلار</option><option value="asset">{tokenName(market?.collateralSymbol??market?.asset??'')}</option></Select></Field>{input('سرمایهٔ فرضی',capital,setCapital,capitalUnit==='asset'?tokenName(market?.collateralSymbol??market?.asset??''):'دلار')}</>}<Field label="سررسید مطلوب"><Select value={days} onChange={e=>setDays(e.target.value)}>{[7,30,60,90].map(n=><option key={n} value={n}>تا {new Intl.NumberFormat('fa-IR').format(n)} روز</option>)}</Select></Field>{input('گس کل دوره',gas,setGas,'دلار','اگر هزینه ندارد: صفر')}{input('هزینهٔ ورود اضافی هر بازار',entrance,setEntrance,'دلار','اگر پرداخت نمی‌شود: صفر')}</div><Disclosure summary="تخصیص و حد زیان سناریو"><div className="grid gap-3 sm:grid-cols-2 py-3">{input('تخصیص مارجین',allocation,setAllocation,'٪')}{input('حد زیان سناریوی نامساعد',risk,setRisk,'٪ بودجه')}</div><p className="text-xs leading-6 text-muted">حد زیان فیلتر سناریو است؛ سفارش توقف زیان نیست. گزینه‌ها جایگزین هم هستند و یک بودجه را هم‌زمان مصرف نمی‌کنند.</p></Disclosure><p className="text-xs text-muted">کارمزد معامله و تسویه خودکار محاسبه می‌شود؛ نگهداری تا سررسید فرض شده است.</p>{mode==='real'&&!budget?.available&&<p className="text-xs text-muted">{!account.root?'ابتدا آدرس عمومی را در حساب من ثبت کنید.':'دادهٔ تازهٔ همین وثیقه لازم است.'} <button className="min-h-11 text-accent" onClick={()=>void refreshBorosAccount(true)}>تازه‌سازی حساب</button></p>}</Surface>;
 const shortlist=[...new Map(candidates.filter(c=>c.result.scenarioMin!==null&&c.result.scenarioMin>=-capitalUsd*(number(risk)??-1)/100).map(c=>[c.m.marketId,c])).values()].slice(0,3);
 const inspect=(id:number,side:BorosDirection='long')=>{const m=markets.find(m=>m.marketId===id);const row=m&&m.tokenId===market?.tokenId?compareWithBudget(m,side,capitalUsd,number(allocation)??0,costs):null;onInspect(id,side,row?{mode,capitalUsd,sizeYu:row.sizeYu,costs}:undefined);};
 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><SegmentedControl label="نمای بازارها" value={view==='all'?'all':'recommend'} onChange={v=>setView(v)} options={[{value:'all',label:'همهٔ بازارها'},{value:'recommend',label:'پیشنهاد برای من'}]}/><Button size="sm" variant={view==='compare'?'primary':'outline'} disabled={selectedMarkets.length<2} onClick={()=>setView('compare')}>مقایسهٔ انتخاب‌ها ({new Intl.NumberFormat('fa-IR').format(selectedMarkets.length)})</Button></div>
 {view==='all'?<Disclosure summary="بودجه و هزینه‌های بررسی">{controls}</Disclosure>:controls}
 <section hidden={view!=='all'}><OpportunitiesTab markets={markets} onInspect={inspect} onRecommend={()=>setView('recommend')} compareIds={compareIds} compareTokenId={market?.tokenId} onCompare={id=>setCompareIds(ids=>ids.includes(id)?ids.filter(v=>v!==id):ids.length<3?[...ids,id]:ids)}/></section>
 <section hidden={view!=='compare'}>{selectedMarkets.length<2?<p className="text-sm text-muted">دو یا سه بازار با وثیقهٔ یکسان انتخاب کنید.</p>:<ComparisonTab active={active&&view==='compare'} markets={selectedMarkets} capitalUsd={capitalUsd} allocationPct={number(allocation)??0} costs={costs} mode={mode} onInspect={onInspect}/>}<Button size="sm" variant="ghost" onClick={()=>setView('all')}>بازگشت به فهرست بازارها</Button></section>
 <section hidden={view!=='recommend'}>{market&&(mode==='real'?<VerifiedOpportunities candidates={candidates.filter(c=>c.result.scenarioMin!==null&&c.result.scenarioMin>= -capitalUsd*(number(risk)??-1)/100)} market={market} marginMode="cross" capitalUsd={capitalUsd} riskPct={number(risk)??NaN} costs={costs} modelFees active={active&&view==='recommend'} onSelect={onSelect}/>:<Surface className="p-4 space-y-3"><h3 className="font-bold">گزینه‌های فرضی با این سرمایه</h3>{shortlist.map(c=><div key={c.m.marketId} className="flex flex-wrap justify-between gap-3 border-b border-divider py-3"><MarketIdentity market={c.m} compact/><div><p className="text-xs text-muted">{c.direction==='long'?'لانگ':'شورت'} · خالص تخمینی تا سررسید</p><MoneyValue value={c.result.net} signed tone="auto"/></div><Button size="sm" variant="outline" onClick={()=>inspect(c.m.marketId,c.direction)}>پیش‌نمایش سناریو</Button></div>)}{!shortlist.length&&<p className="text-sm text-muted">بودجه، هزینه‌ها، سررسید و حد زیان را بررسی کنید؛ گزینهٔ فرضی مناسب پیدا نشد.</p>}<p className="text-xs text-muted">قیمت اجرای رسمی و وضعیت حساب واقعی در این پیشنهاد فرضی لحاظ نشده‌اند.</p></Surface>)}</section>
 </div>;
}
