import seed from '@/shared/domain/pendleLogoSeed.json';
import { pendleMarketLogos } from '@/shared/domain/pendleLogos';
import { describe, expect, it } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
import { TokenLogo } from './EntityLogo';
import { YieldTokenLabel, YieldTokenMaturity } from './YieldTokenLabel';
import { yieldTokenIdentity } from './YieldTokenMark';
describe('generic Persian receipt identities',()=>{
 it('resolves original sUSDx and sUSDat logos by their actual Ethereum YT contract even with no wallet icon',()=>{for(const underlying of ['sUSDx','sUSDat']){const token=pendleMarketLogos(seed).find(t=>t.chainId===1&&t.kind==='YT'&&t.underlying===underlying)!;expect(token).toBeTruthy();const html=renderToStaticMarkup(<TokenLogo logo={null} symbol={`YT-${underlying}-03DEC2026`} chain="ethereum" contract={token.contract}/>);expect(html).toContain(`src="${token.logo}"`);expect(html).toContain('data-yield-logo-badge="YT"');}});
 it('parses future YT, PT and LP markets and translates every Latin letter',()=>{for(const kind of ['YT','PT','LP']){const i=yieldTokenIdentity(`${kind}-sUSDx-03DEC2026`)!;expect(i.kind).toBe(kind);expect(i.underlying).toBe('sUSDx');expect(i.underlyingFa).toBe('اس‌یو‌اس‌دی‌اکس');expect(i.maturityFa).toBe('۱۲ آذر ۱۴۰۵');expect(i.nameFa).not.toMatch(/[A-Za-z]/);}expect(yieldTokenIdentity('PYTH')).toBeNull();expect(yieldTokenIdentity('LPT')).toBeNull();expect(yieldTokenIdentity('PENDLE-LPT')).toMatchObject({kind:'LP',nameFa:'ال‌پی'});});
 it('supports provider date formats, names as date fallback and no invented expiry',()=>{for(const date of ['30DEC2026','2026-12-30','2026/12/30','20261230','30 Dec 2026','30DEC26'])expect(yieldTokenIdentity(`PT-USDe-${date}`)?.maturityFa).toBe('۹ دی ۱۴۰۵');expect(yieldTokenIdentity('YT')).toMatchObject({kind:'YT',nameFa:'وای‌تی',maturity:null});expect(yieldTokenIdentity('LP-NEW','Pendle LP NEW-2028-01-01')?.maturity).toBe(Date.UTC(2028,0,1));for(const date of ['31FEB2026','29FEB2027','2026-13-01','20260231'])expect(yieldTokenIdentity(`YT-NEW-${date}`)?.maturity).toBeNull();expect(yieldTokenIdentity('YT-NEW-29FEB2028')?.maturity).toBe(Date.UTC(2028,1,29));});
 it('shows the asset logo with the actual network badge rather than a synthesized YT/PT logo',()=>{for(const kind of ['YT','PT','LP'])for(const [networkName,networkLogo]of[['اتریوم','/logos/chain-1.svg'],['آربیتروم','/logos/chain-arbitrum.svg']]){const html=renderToStaticMarkup(<TokenLogo logo="/logos/token-usdc.svg" symbol={`${kind}-sUSDat-14JAN2027`} networkName={networkName} networkLogo={networkLogo}/>);expect(html).toContain('src="/logos/token-usdc.svg"');expect(html).toContain(`src="${networkLogo}"`);expect(html).toContain(`data-yield-token="${kind}"`);expect(html).toContain(`data-yield-logo-badge="${kind}"`);expect(html).not.toContain('<svg');}});
 it('does not invent a network for grouped receipts; unknown logos have a readable fallback',()=>{const html=renderToStaticMarkup(<TokenLogo logo={null} symbol="LP-NEW-2028-01-01"/>);expect(html).not.toContain('token-network-badge');expect(html).toContain('ان‌ای‌دبلیو');expect(renderToStaticMarkup(<TokenLogo logo="/logos/token-eth.svg" symbol="ETH"/>)).toContain('src="/logos/token-eth.svg"');});
 it('renders Persian badge and separate Solar Hijri maturity',()=>{const html=renderToStaticMarkup(<><YieldTokenLabel symbol="YT-sUSDat-14JAN2027"/><YieldTokenMaturity symbol="YT-sUSDat-14JAN2027"/></>);expect(html).toContain('وای‌تی');expect(html).toContain('اس‌یو‌اس‌دی‌ای‌تی');expect(html).toContain('سررسید ۲۴ دی ۱۴۰۵');expect(renderToStaticMarkup(<YieldTokenMaturity symbol="LP-NEW"/>)).toContain('سررسید نامشخص');});
});
